### ISSUE TITLE
Update README for Improved Documentation

### ISSUE THREAD

**Issue by adarsh-site** [a-box31/Arte#8]
Clear and well-structured documentation is crucial for users and contributors to understand the project, its purpose, and how to get started

**Comment by adarsh-site** [comment]
please assign this issue to me.

**Comment by a-box31** [comment]
I look forward to seeing your documentation. Sorry for the mess... and thank you for the help!

**Comment by adarsh-site** [comment]
hlo @a-box31 , I have created a pr. please check it and let me know the feedback.
